import java.util.*;

public class Main {
    public static void main(String[] args) {
       
      int a = 10;
      int b = 20;
      System.out.println(a);
      System.out.println("---");
      System.out.println(a++);
      System.out.println(++a);
      System.out.println();
      System.out.println(b);
      System.out.println("---");
      System.out.println(b++);
      System.out.println(++b);
  }
}
